### ISSUE TITLE
Add deep links into the styleguide for each cop in `config/default.yml`

### ISSUE THREAD

**Issue by issyl0** [github/rubocop-github#133]
In #132 we linked each styleguide rule to its corresponding RuboCop rule(s).

RuboCop has functionality where a `StyleGuide: <link>` config for each cop will show the link to the styleguide when there's a violation or a user just wants to know what cops are enabled. We haven't added all of these cross-references yet, and we should finish off.

For each of the rules in [the styleguide](https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md), add `StyleGuide:` under its cop name in `config/default.yml`. If it doesn't have a config, add the full stanza. For example:

```yaml
# This rule is specifically disabled, but we still want it to have a styleguide link.
Layout/LineLength:
  Enabled: false
  StyleGuide: 

# Pretend this rule didn't exist in the config file before, as an example. Since it's a RuboCop default cop and doesn't need any special configuration. But, we still want a styleguide link, so add the whole rule name.
Layout/EmptyLineBetweenDefs:
  StyleGuide: https://github.com/github/rubocop-github/blob/main/STYLEGUIDE.md#empty-lines-def
```
